title: My awesome homepage
author: xyao99
email: xiuyaoxyz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for my awesome homepage. Welcome!

# social links
twitter_username: xyaoxyz # DO NOT include the @ character, or else the build will fail!
github_username:  xyao99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
